# Generated by Django 6.0.7 on 2026-07-26 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='GenreIndex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'genre_index',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'instrument',
            },
        ),
        migrations.CreateModel(
            name='GenreHierarchy',
            fields=[
                ('pk', models.CompositePrimaryKey('genre', 'parent', blank=True, editable=False, primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(db_column='genre', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musical_genres_rag.genre')),
                ('parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musical_genres_rag.genre')),
            ],
            options={
                'db_table': 'genre_hierarchy',
            },
        ),
        migrations.AddField(
            model_name='genre',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='musical_genres_rag.GenreHierarchy', through_fields=('genre', 'parent'), to='musical_genres_rag.genre'),
        ),
        migrations.CreateModel(
            name='InstrumentGenres',
            fields=[
                ('pk', models.CompositePrimaryKey('instrument', 'genre', blank=True, editable=False, primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(db_column='genre', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musical_genres_rag.genre')),
                ('instrument', models.ForeignKey(db_column='instrument', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musical_genres_rag.instrument')),
            ],
            options={
                'db_table': 'instrument_genres',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='genres',
            field=models.ManyToManyField(related_name='instruments', through='musical_genres_rag.InstrumentGenres', through_fields=('instrument', 'genre'), to='musical_genres_rag.genre'),
        ),
    ]
