# Generated by Django 6.0.7 on 2026-07-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0002_bm25_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retriever', models.CharField(max_length=64)),
                ('k', models.PositiveSmallIntegerField()),
                ('embedding_model', models.CharField(max_length=128)),
                ('hit_rate', models.FloatField(null=True)),
                ('mrr', models.FloatField(null=True)),
                ('report', models.JSONField()),
            ],
            options={
                'db_table': 'evaluation_run',
            },
        ),
    ]
