# Generated by Django 6.0.7 on 2026-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0003_evaluationrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrun',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
