# Generated by Django 6.0.7 on 2026-07-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0006_register_existing_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrun',
            name='type',
            field=models.CharField(choices=[('retrieval', 'Retrieval'), ('rag', 'Rag')], default='rag', max_length=32),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['type', '-created_at'], name='evaluation_run_type_created'),
        ),
    ]
