# Generated by Django 6.0.7 on 2026-07-30 18:44

import datetime
from django.db import migrations, models

# Nothing recorded when the feedback already stored was given, so every existing row is dated the
# moment this ran. The index is what the judgements page reads them back in, newest first.


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 30, 18, 44, 11, 419569, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created', '-id'], name='feedback_created'),
        ),
    ]
