# Generated by Django 6.0.7 on 2026-07-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0010_feedback_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'judge_batch',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='judge_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judgements', to='musical_genres_rag.judgebatch'),
        ),
    ]
