# Generated by Django 6.0.7 on 2026-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0012_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='input_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='output_tokens',
            field=models.IntegerField(null=True),
        ),
    ]
