# Generated by Django 6.0.7 on 2026-07-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0013_feedback_cost'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='feedback_conversation_source',
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('conversation',), name='feedback_conversation'),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='source',
        ),
    ]
