# Generated by Django 6.0.7 on 2026-07-31 16:00

from django.db import migrations, models

from musical_genres_rag.Rag import cost

"""Lifts what every stored answer took and spent out of the JSON it was recorded in.

Nothing new is worked out here that the answer did not already say: the time and the two counts are
read back as the call reported them, and the cost is what those counts come to at what the model
charges. The model itself stays empty, because which one answered was never recorded and a guess
would have the dashboard claiming a history it does not have.
"""
def registerStoredMetrics(apps, schema_editor):
    Conversation = apps.get_model('musical_genres_rag', 'Conversation')

    for conversation in Conversation.objects.all():
        answer = conversation.answer or {}
        input_tokens = answer.get('input_tokens')
        output_tokens = answer.get('output_tokens')

        Conversation.objects.filter(pk = conversation.pk).update(
            duration = answer.get('duration'),
            input_tokens = input_tokens,
            output_tokens = output_tokens,
            # Priced only where both counts are there to price
            cost = cost(input_tokens, output_tokens) if input_tokens is not None and output_tokens is not None else None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('musical_genres_rag', '0014_drop_feedback_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='input_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='model',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='output_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-created', '-id'], name='conversation_created'),
        ),
        # Nothing to undo: dropping the columns is what takes these back off
        migrations.RunPython(registerStoredMetrics, migrations.RunPython.noop),
    ]
