-- Seed data, loaded by the postgres entrypoint right after schema.sql.
-- The CSVs are generated by scripts/generate-dataset.py from a MusicBrainz dump and are
-- mounted read-only at /data (see compose.yml).
--
-- Parent tables first, so the foreign keys resolve.

COPY genre             (id, name, description) FROM '/data/genre.csv'              WITH (FORMAT csv, HEADER true);
COPY instrument        (id, name, description) FROM '/data/instrument.csv'         WITH (FORMAT csv, HEADER true);
COPY genre_hierarchy   (genre, parent)         FROM '/data/genre_hierarchy.csv'    WITH (FORMAT csv, HEADER true);
COPY instrument_genres (instrument, genre)     FROM '/data/instrument_genres.csv'  WITH (FORMAT csv, HEADER true);

-- The ids above are explicit, so move the identity sequences past them or the
-- next plain INSERT would collide with a seeded row.
SELECT setval(pg_get_serial_sequence('genre', 'id'), (SELECT max(id) FROM genre));
SELECT setval(pg_get_serial_sequence('instrument', 'id'), (SELECT max(id) FROM instrument));
